# -*- coding: utf-8 -*-
"""Email_extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hiaYy3cN3m8t_oJDOWGAAixP3iBTc5LA
"""

import re

String1 = "Hello!, this is Mythili, you can contact me in this email: mythilisouxxxx@gmail.com"
match = re.findall('\S+@\S+', String1)

print(match)