# -*- coding: utf-8 -*-
"""NLP re 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZN6D8GUd8-BGMYsn-PN-f0Xm6Gseqjgr

Search function in NLP
"""

import re

strings = "Hello, this is Mythili! How are you?"
match = re.search(r'Mythili',strings)

print("Match started", match.start())
print("Match ended", match.end())
print("Match found", match.group())

strings1 = "Mythili.Srajan"

match = re.search(r'.', strings1)
print(match)

match = re.search(r'\.', strings1)
print(match)

strings2 = "Hola!, soy Mythili, una Estudente, mi leers Computodora"

match = "[r-z]"
print(re.findall(match, strings2))

strings3 = "Hola! Everyone, mi nombre es Mythili"
match = re.search(r'Mythili$', strings3)

if match:
  print("Matched")
else:
  print("Not found")